change-id = "ignore"

[build]
build = "i586-alpine-linux-musl"
host = ["i586-alpine-linux-musl"]
target = ["i586-alpine-linux-musl"]
extended = true
tools = ["cargo", "rustfmt", "clippy", "rustdoc"]
submodules = false
locked-deps = true
rustc = "/usr/bin/rustc"
cargo = "/usr/bin/cargo"

[llvm]
# Usar el LLVM del sistema (instalado por apk) para no compilarlo desde fuente
llvm-config = "/usr/bin/llvm-config"
download-ci-llvm = false

[rust]
download-rustc = false
debuginfo-level = 0
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16          # Más paralelismo durante la compilación
lto = false                 # Desactivado para mayor velocidad (si quieres binarios más pequeños, pon true)

[target.i586-alpine-linux-musl]
cc = "gcc"
cxx = "g++"
ar = "ar"
linker = "gcc"
rustflags = [
    "-Ctarget-cpu=i686",
    "-Ctarget-feature=+sse,+sse2"
]