change-id = "ignore"

[build]
build = "i586-alpine-linux-musl"
host = ["i586-alpine-linux-musl"]
target = ["i686-unknown-linux-musl"]      # <-- CAMBIO: target estándar
extended = true
tools = ["cargo", "rustfmt", "clippy", "rustdoc"]
submodules = false
locked-deps = true
rustc = "/usr/bin/rustc"
cargo = "/usr/bin/cargo"

[llvm]
download-ci-llvm = false
ninja = true

[rust]
download-rustc = false
# build-std = true   # ELIMINADO (no es válido)
debuginfo-level = 0
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16
lto = "off"

[target.i686-unknown-linux-musl]          # <-- CAMBIO: sección del target estándar
cc = "gcc"
cxx = "g++"
ar = "ar"
linker = "gcc"
llvm-config = "/usr/bin/llvm-config"
rustflags = [
    "-Ctarget-cpu=i686",
    "-Ctarget-feature=+sse,+sse2"
]